version: '2.4'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "8081:5432"

  inside-demo:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: inside-container
    image: inside-demo:1
    ports:
      - "8082:8082"

