version: '2.4'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  inside-demo:
    container_name: inside-container
    image: inside:demo
    ports:
      - "8081:8081"
    depends_on:
      - postgres

